name: ${name}
version: ${version}
main: uk.protonull.smithery.Smithery
author: Protonull
authors: []
api-version: 1.18
depend: [CivModCore]
permissions:
  smithery.admin:
    default: op
  smithery.smelt:
    default: true
  smithery.cool:
    default: true
  smithery.checktime:
    default: true
  smithery.remove:
    default: true
  smithery.inspect:
    default: op